### PR TITLE
add options id

### PR DESCRIPTION
**Pull request by PhilippeHidayat**
adding options "id" in-case the is link that use id in the pagination link

### CODE REVIEW

**Comment by jimf** [comment]
I'm not sure this really belongs in the helper, given that `id` isn't changing anywhere and isn't really tied to any of the pagination logic. I'd recommend instead providing it with the rest of your template data and referencing it directly. For example:

```js
var html = template({
  id: myId,
  pagination: {
    page: 3,
    pageCount: 10
  }
});
```

```html
{{#paginate pagination type="last"}}
  <li id={{../id}}{{#if disabled}} class="disabled"{{/if}}><a href="?p={{n}}">Last</a></li>
{{/paginate}}
```

Let me know if I'm missing something.

**Comment by PhilippeHidayat** [comment]
I did tried referencing that "id" directly, but handlebars can't read it when it is placed between {{#paginate ...}} and {{/paginate}}. No idea why.  Thats why i tried to pass it through the helper.

**Comment by jimf** [comment]
Ah, yes, that's the way Handlebars deals with scoping. When inside the `paginate` block expression, the context changes. Note in my example that I'm using `../id`. That instructs the engine to use `id` in the scope above. See the "Handlebars Paths" section of the [official docs](http://handlebarsjs.com/) for more.

**Comment by jimf** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
