### PR TITLE
Add "first" and "last" types

### PR DESCRIPTION
**Pull request by jimf**
Add handling for "first" and "last" page types.

Note: I took the liberty of adding tests. I hope you're okay with this. I checked out some of your other stuff, and found you were using mocha (+ chai) in one of your more recent projects, so I went with mocha, but I kept it as light as possible. If you don't want the tests for whatever reason, but are cool with the first/last feature, I can pull those commits out. I've tried to keep the styling as close to the existing as possible.

### CODE REVIEW

**Comment by olalonde** [comment]
Thanks @jimf . Of course adding tests is a good idea and mocha/chai is a good choice. Since I don't use this module much these days, I've added you as a collaborator so you can merge changes by yourself :) Could you document what you implemented in the README so others can use it? Cheers.

**Comment by jimf** [comment]
Awesome, will do, thanks! How do you want to handle version cutting / npm publishing?

**Comment by olalonde** [comment]
I can let you handle that as well :) What's your npm account? (`npm whoami`)

**Comment by jimf** [comment]
Sounds good. I'm jimf on npm as well.

**Comment by olalonde** [comment]
@jimf you should be able to publish now.

**Pull request merged**
