### PR TITLE
update npm/bower version

### PR DESCRIPTION
**Pull request by Torwori**
Took me about an hour to figure out why it wasn't working, turns out I accidentally passed strings. Hopefully this saves someone some time.

### CODE REVIEW

**Comment by zenorocha** [comment]
A better approach to this would be throwing an error when argument is not a number.

**Comment by Torwori** [comment]
Seems like npm installs a version prior to 566f347b8fcfa658eed28d51a56b94675792423e where this bug was fixed. Updating the version should fix that.

**Comment by olalonde** [comment]
Ooops.. I think your commit should be in 0.0.3. I can add you as a committer if you'd like as I've not used this plugin in a long time.

**Comment by Torwori** [comment]
Sure, but there isn't really much I would do, your plugin does it's job perfectly.

**Comment by olalonde** [comment]
@Torwori thanks :) Added you to collaborators just in case.

**Pull request merged**
